name = "dropdown-email-worker"
main = "worker.js"
compatibility_date = "2025-08-11"
type = "javascript"

account_id = "85221db225a51b1c70076848e8c20111"

workers_dev = true

[[email]]
binding = "SEND_EMAIL"